PROJECT_DIR=/home/user/Music/projects/C
SRC_DIR=$(PROJECT_DIR)/src
TEST_DIR=$(PROJECT_DIR)/test
# specify where the source code and includes are located
INCLUDE_DIRS=$(SRC_DIR)
SRC_DIRS=$(SRC_DIR)
 
# specify where the test code is located
TEST_SRC_DIRS = $(TEST_DIR)
 
# what to call the test binary
TEST_TARGET=example
 
# where the cpputest library is located
CPPUTEST_HOME=/home/user/Music/projects/C/test/unitTestLibrary/cppUtest/cpputest_build
 
# run MakefileWorker.mk with the variables defined here
include MakefileWorker.mk
